### ISSUE TITLE
Jenkins update center not showing newer releases

### ISSUE THREAD

**Issue by LucasSymons** [jenkinsci/gitlab-plugin#1027]
## Issue
The Jenkins update centre still shows version 1.5.13 as the current build of the plugin. 
My team is hesitant to build from the source as they are not sure if it will break future update integration or cause other issues, but we would really enjoy some of the latest fixes. 
Would it be possible to have 1.5.17 pushed to the Jenkins update centre? 

### Context
- **Jenkins Gitlab plugin version**: [1.5.13](https://plugins.jenkins.io/gitlab-plugin/)
- **Github version**: [1.5.17](https://github.com/jenkinsci/gitlab-plugin/releases/tag/gitlab-plugin-1.5.17)
- **Jenkins version**: 2.218
- **Job type**: Publish???

**Comment by markjacksonfishing** [comment]
@Akin2Silver yeah, there are some problems with the Jenkins infra.. As soon as that gets sorted out, I will push this version to the update center

**Comment by LucasSymons** [comment]
> @Akin2Silver yeah, there are some problems with the Jenkins infra.. As soon as that gets sorted out, I will push this version to the update center

Thanks very much! I really appreciate it.

**Comment by jblamotte** [comment]
Any news about that ?

**Comment by mat1e** [comment]
@markyjackson-taulia, do you have any news ?

**Comment by markjacksonfishing** [comment]
Hi all,
I will hopefully have this out this weekend to the update center

**Comment by reinholdfuereder** [comment]
(See #1018)

**Comment by artbycrunk** [comment]
any update on this? is it an issue on the jenkins update center end?

**Comment by youaresodalgona** [comment]
Not solved yet?

**Comment by LucasSymons** [comment]
Is there anything I can do to help this one along?

**Comment by markjacksonfishing** [comment]
We had a few infra issues and have been sick. I will get back on this this week

**Comment by LucasSymons** [comment]
Just wanted to follow up on this one, see if there was any help i could provide even if you just need me to dig through some docs or some thing?

**Comment by reinholdfuereder** [comment]
@markyjackson-taulia \*Begging\*

(1.5.17 was released on 09 Feb 2020: https://github.com/jenkinsci/gitlab-plugin/releases/tag/gitlab-plugin-1.5.17)

Maybe as already mentioned in #1018 a very able Jenkins core dev/expert like @oleg-nenashev can help? (Extremely naive guess: May that be because of the version being a "snapshot" only in the "pom.xml"? Cf. `<version>1.5.17-SNAPSHOT</version>`)

**Comment by markjacksonfishing** [comment]
Will take a look this weekend

**Comment by jluk-scms** [comment]
@markyjackson-taulia I'm willing to help you with this, but I need some hints about what needs to be done :)

**Comment by markjacksonfishing** [comment]
Thank you kindly. The issue is with deploying to artifactory. I will work on that this weekend

**Comment by jluk-scms** [comment]
Hi @markyjackson-taulia , how it's going?

**Comment by jluk-scms** [comment]
@omehegan Maybe you can help here. I found your username in the jenkins-infra repo: https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-gitlab-plugin.yml

I'm still willing to help if any work is needed to be done to push this forward, just need pointers where to look. Cheers.

**Comment by markjacksonfishing** [comment]
> @omehegan Maybe you can help here. I found your username in the jenkins-infra repo: https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-gitlab-plugin.yml
> 
> 
> 
> I'm still willing to help if any work is needed to be done to push this forward, just need pointers where to look. Cheers.

The problem is with how the HPI artifact is pushed to artifactory. I am working to fix this. Just need a little more time.
Appreciate everyone and sorry this has taken so long.

**Comment by kanata2** [comment]
Any news about this problem? (Sorry to rush you...)

**Comment by jeremy-albinet** [comment]
Can we help you on this?

**Comment by frank-aurich** [comment]
Can we please get some update on this issue? 
The last version was released in Feburary, 7 months ago, but unless you build it yourself you cannot use it because the Jenkins plugin system doesn't know about the latest version.

Can we assist in any way in fixing this issue?

**Comment by sandeepnagori87** [comment]
@markyjackson-taulia  Would appreciate if this can be done ASAP.thanks

**Comment by sandeepnagori87** [comment]
> @markyjackson-taulia Would appreciate if this can be done ASAP.thanks

Seems @markyjackson-taulia  step back from open source projects. @MarkEWaite  Could you please help to have 1.5.17 gitlab plugin in jenkins update center. Thanks a lot.

**Comment by MarkEWaite** [comment]
Thanks for asking, @sandeepnagori87. Unfortunately, I'm not available to assist with this plugin.  I fear that my assistance would cause more harm than help.

I'm not a frequent user of GitLab and cannot commit the time and energy necessary to become experienced enough to be a viable maintainer of the GitLab plugin.

The Jenkins project encourages those interested in a plugin to volunteer to maintain that plugin by ["adopting the plugin"](https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/).  If you're a frequent user of the GitLab plugin and are interested in assisting with its development, please use the ["adopt a plugin"](https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/) process to ask to be allowed to help.

If you need the 1.5.17 release sooner than ["adopt a plugin"](https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/)  allows, you could checkout the 1.5.17 tag from git, build the plugin from source code, and use that plugin locally on your instance.  If you detect issues with that version, you could propose fixes for those issues as pull requests to the plugin.

In my case, I needed a version of the GitLab plugin that did not bundle an outdated version of JGit.  I created a [branch](https://github.com/MarkEWaite/gitlab-plugin/tree/1.5.13-rely-on-git-client-to-provide-jgit) from 1.5.13 with a [commit](https://github.com/MarkEWaite/gitlab-plugin/commit/66a868d2e6e7d88270ccb8130c5d00de4db0b82e) that removed JGit from the packaging, then built that version and placed it in my [Docker image](https://github.com/MarkEWaite/docker-lfs/blob/lts-with-plugins/ref/plugins/gitlab-plugin.jpi).  If your needs are the same as mine, you're welcome to install that plugin version in your environment.

In case someone needs a locally built version of the 1.5.17 GitLab plugin and isn't able to create it themselves, I've uploaded a version that I built locally with JDK 8u282.  The version I built locally does not meet my needs because it still includes JGit 3.5.2.  I don't know if it will meet the needs of others.

[gitlab-plugin-1.5.17-SNAPSHOT.zip](https://github.com/jenkinsci/gitlab-plugin/files/5893932/gitlab-plugin-1.5.17-SNAPSHOT.zip)

**Comment by sandeepnagori87** [comment]
> Thanks for asking, @sandeepnagori87. Unfortunately, I'm not available to assist with this plugin. I fear that my assistance would cause more harm than help.
> 
> I'm not a frequent user of GitLab and cannot commit the time and energy necessary to become experienced enough to be a viable maintainer of the GitLab plugin.
> 
> The Jenkins project encourages those interested in a plugin to volunteer to maintain that plugin by ["adopting the plugin"](https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/). If you're a frequent user of the GitLab plugin and are interested in assisting with its development, please use the ["adopt a plugin"](https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/) process to ask to be allowed to help.
> 
> If you need the 1.5.17 release sooner than ["adopt a plugin"](https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/) allows, you could checkout the 1.5.17 tag from git, build the plugin from source code, and use that plugin locally on your instance. If you detect issues with that version, you could propose fixes for those issues as pull requests to the plugin.
> 
> In my case, I needed a version of the GitLab plugin that did not bundle an outdated version of JGit. I created a [branch](https://github.com/MarkEWaite/gitlab-plugin/tree/1.5.13-rely-on-git-client-to-provide-jgit) from 1.5.13 with a [commit](https://github.com/MarkEWaite/gitlab-plugin/commit/66a868d2e6e7d88270ccb8130c5d00de4db0b82e) that removed JGit from the packaging, then built that version and placed it in my [Docker image](https://github.com/MarkEWaite/docker-lfs/blob/lts-with-plugins/ref/plugins/gitlab-plugin.jpi). If your needs are the same as mine, you're welcome to install that plugin version in your environment.
> 
> In case someone needs a locally built version of the 1.5.17 GitLab plugin and isn't able to create it themselves, I've uploaded a version that I built locally with JDK 8u282. The version I built locally does not meet my needs because it still includes JGit 3.5.2. I don't know if it will meet the needs of others.
> 
> [gitlab-plugin-1.5.17-SNAPSHOT.zip](https://github.com/jenkinsci/gitlab-plugin/files/5893932/gitlab-plugin-1.5.17-SNAPSHOT.zip)

Thanks Mark.I will have a look on "adopt a plugin" .Since this is was little urgent I try to use your private 1.5.17 gitlab plugin unfortunately I still see same issues [Jenkins triggers for non code changes]which got fixed in https://github.com/jenkinsci/gitlab-plugin/pull/998.

@ababushk Can you try to use this plug-in and see if it solves issues at your end.

**Comment by sandeepnagori87** [comment]
> > Thanks for asking, @sandeepnagori87. Unfortunately, I'm not available to assist with this plugin. I fear that my assistance would cause more harm than help.
> > I'm not a frequent user of GitLab and cannot commit the time and energy necessary to become experienced enough to be a viable maintainer of the GitLab plugin.
> > The Jenkins project encourages those interested in a plugin to volunteer to maintain that plugin by ["adopting the plugin"](https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/). If you're a frequent user of the GitLab plugin and are interested in assisting with its development, please use the ["adopt a plugin"](https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/) process to ask to be allowed to help.
> > If you need the 1.5.17 release sooner than ["adopt a plugin"](https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/) allows, you could checkout the 1.5.17 tag from git, build the plugin from source code, and use that plugin locally on your instance. If you detect issues with that version, you could propose fixes for those issues as pull requests to the plugin.
> > In my case, I needed a version of the GitLab plugin that did not bundle an outdated version of JGit. I created a [branch](https://github.com/MarkEWaite/gitlab-plugin/tree/1.5.13-rely-on-git-client-to-provide-jgit) from 1.5.13 with a [commit](https://github.com/MarkEWaite/gitlab-plugin/commit/66a868d2e6e7d88270ccb8130c5d00de4db0b82e) that removed JGit from the packaging, then built that version and placed it in my [Docker image](https://github.com/MarkEWaite/docker-lfs/blob/lts-with-plugins/ref/plugins/gitlab-plugin.jpi). If your needs are the same as mine, you're welcome to install that plugin version in your environment.
> > In case someone needs a locally built version of the 1.5.17 GitLab plugin and isn't able to create it themselves, I've uploaded a version that I built locally with JDK 8u282. The version I built locally does not meet my needs because it still includes JGit 3.5.2. I don't know if it will meet the needs of others.
> > [gitlab-plugin-1.5.17-SNAPSHOT.zip](https://github.com/jenkinsci/gitlab-plugin/files/5893932/gitlab-plugin-1.5.17-SNAPSHOT.zip)
> 
> Thanks Mark.I will have a look on "adopt a plugin" .Since this is was little urgent I try to use your private 1.5.17 gitlab plugin unfortunately I still see same issues [Jenkins triggers for non code changes]which got fixed in #998.
> 
> @ababushk Can you try to use this plug-in and see if it solves issues at your end.

Sorry my mistake. I did not check "Build only if new commits were pushed to Merge Request" option in jenkins UI before doing test.

Looks like it is working fine. Thanks alot. If someone can push it in jenkins update center then it would be great.:)
--

**Comment by MarkEWaite** [comment]
> ## Looks like it is working fine. Thanks alot. If someone can push it in jenkins update center then it would be great.:)

That's what maintainers do.  If you'd like to become a maintainer, ["adopt a plugin"](https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/) is the path to become a maintainer.

**Comment by sandeepnagori87** [comment]
> > ## Looks like it is working fine. Thanks alot. If someone can push it in jenkins update center then it would be great.:)
> 
> That's what maintainers do. If you'd like to become a maintainer, ["adopt a plugin"](https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/) is the path to become a maintainer.

Sure. I will have a look.
BTW I was trying to build plugin locally but got some connection issues e.g. . Appreciate your help

**Failed tests:
com.dabsquared.gitlabjenkins.connection.GitLabConnectionConfigTest.doCheckConnection_proxy(com.dabsquared.gitlabjenkins.connection.GitLabConnectionConfigTest)
  Run 1: GitLabConnectionConfigTest.doCheckConnection_proxy:102
Expected: a string containing "Connection refused"
     but: was "Client error: HTTP 404 Not Found"**

**Comment by MarkEWaite** [comment]
I don't know the source code of the plugin.  It may be assuming there is a GitLab server at a specific URL or it may be failing to create a mock GitLab server.

**Comment by Stikus** [comment]
Plugin is looking for adoption: #1098 - FYI

**Comment by omehegan** [comment]
If someone can fix the broken master branch build, I can at least get a release out. Any volunteers?

**Comment by MarkEWaite** [comment]
@omehegan I've submitted ##1106 that fixes compilation on the master branch.  I don't know if it passes tests.  Too late in my day to check that.  I tried to find the minimum subset of changes that would fix compilation before end of day.

**Comment by bulanovk** [comment]
@omehegan Master brach already fixed in this MR https://github.com/jenkinsci/gitlab-plugin/pull/1103

**Comment by omehegan** [comment]
1.5.19 was finally released successfully yesterday! Thanks to everyone who helped resolve issues to get this done.
