### ISSUE TITLE
Avoid building master, just build MRs

### ISSUE THREAD

**Issue by bmaehr** [jenkinsci/gitlab-plugin#1037]
### Context
- **Gitlab plugin version**: 1.5.13
- **Gitlab version**:  11.10.0-ee
- **Jenkins version**: 2.204.4

### Problem description

I would just like avoid building master (because this is done by an other job with different parameters) but of course building MR which are going to be merged to master. How is it possible to configure this with the plugin?

**Comment by gavinc-git** [comment]
@bmaehr 

Within your repository, you need to generate a webhook. To do so in your Jenkins 'Configure', scroll down and you will see the following under 'Build Triggers':

![image](https://user-images.githubusercontent.com/23266123/79966763-d195e580-8485-11ea-90da-a83658f5e9b9.png)

Enable this, and copy the URL shown.

For MR only, untick the 'Push' option:

![image](https://user-images.githubusercontent.com/23266123/79966876-fab67600-8485-11ea-81f1-4ab9d58614a0.png)

On the 'Secret Token' click generate, and take not of this.

Back to your respository -> Configure the webhook:

![image](https://user-images.githubusercontent.com/23266123/79967040-39e4c700-8486-11ea-9322-3937e9e7155a.png)

Once saved, you should now get a CI pipe kicking off when there is an open MR. Also any further pushes to this MR will trigger the pipeline to run

I hope this helps you.

**EDIT: As i missed something:

On the jenkins configuration where you specify the branch to build put this:

![image](https://user-images.githubusercontent.com/23266123/79967598-f0e14280-8486-11ea-929f-39b11b0c5afa.png)

Under the advanced options for the repo checkout:

![image](https://user-images.githubusercontent.com/23266123/79967746-25ed9500-8487-11ea-9c16-c97050a739ab.png)

to copy paste [remove quotes] -> "+refs/heads/*:refs/remotes/origin/* +refs/merge-requests/*/head:refs/remotes/origin/merge-requests/*"

**Comment by bmaehr** [comment]
@squidgegmc Thanks for your documentation how to set up. 
I have the connection already running, the request is exactly like written in my question: The MR (MR with master as target branch) or a push to an other branch than master should still be built, but pushes on master (or after merging the MR to master) should not be done.

**Comment by gavinc-git** [comment]
@bmaehr 

Sorry your initial question does not mention pushes:

> Problem description
 I would just like avoid building master (because this is done by an other job with different parameters) but of course building MR which are going to be merged to master. How is it possible to configure this with the plugin?

You will need to alter your webhook to allow `push`, then alter your Jenkins configuration:
![image](https://user-images.githubusercontent.com/23266123/80010889-01171300-84c3-11ea-8c36-c27451eecf1b.png)
1. This will trigger the hook on PUSH requests (you will need to change the checkout branch as i have previously explained)

2. Leave this disabled - enabling this will trigger the CI upon MR completing.

Without seeing your webhook setup, and Jenkins config its alittle difficult to assit further.

**Comment by bmaehr** [comment]
Ok, thank you, I will try it.
My first trys have been to use the "filter branches by name" configuration and just add "master" to it. But that doesn't work, because of the addition that it filters also merge requests with the configured branch name as target.
