### ISSUE TITLE
Multi configuration project

### ISSUE THREAD

**Issue by florentvaldelievre** [jenkinsci/gitlab-plugin#114]
Hello,

I have an issue with gitlab plugin and multi configuration projects. I have tested with plugin 1.1.26 and 1.1.1 unsuccessfully. Does this plugin works in multi configuration mode ?

**Gitlab plugin 1.1.26 and Multi configuration project scenarios**
1. http://jenkins:8080/project/test2-multiconfig/builds/e38ea80fc7b748ff9556e1102c97a832f0a2b1a1 -> 200 OK, but blank page
2. http://jenkins:8080/project/test2-multiconfig/builds/e38ea80fc7b748ff9556e1102c97a832f0a2b1a1/status.json -> {"sha":"e38ea80fc7b748ff9556e1102c97a832f0a2b1a1","status":"pending"} [ Not relevant status ]
3. http://jenkins:8080/project/test2-multiconfig/builds/status.png?sha1=e38ea80fc7b748ff9556e1102c97a832f0a2b1a1 -> Image with build status "unknown" [ Not relevant status ]

**Gitlab plugin 1.1.1 and Multi configuration project scenarios**
1. http://jenkins:8080/project/test2-multiconfig/builds/e38ea80fc7b748ff9556e1102c97a832f0a2b1a1 -> 404 not found
2. http://jenkins:8080/project/test2-multiconfig/builds/e38ea80fc7b748ff9556e1102c97a832f0a2b1a1/status.json -> 404 not found
3. http://jenkins:8080/project/test2-multiconfig/builds/status.png?sha1=e38ea80fc7b748ff9556e1102c97a832f0a2b1a1 -> 404 not found

**Comment by omehegan** [comment]
@florentvaldelievre can you elaborate on what the bug is exactly? Do commits/MRs trigger builds, or not? Does the build status display in Gitlab, or not? What version of Gitlab are you using?

**Comment by omehegan** [comment]
I'm pretty sure the plugin does not work at all with matrix/multi configuration jobs. @florentvaldelievre can you give me any more detail?

**Comment by omehegan** [comment]
The plugin does not support matrix/multi-configuration jobs. IMO the way forward is to use Pipeline jobs instead. They are much more flexible and powerful than matrix, and plugin support for them is being pushed much more strongly in the community. The gitlab plugin supports them as of version 1.1.32.

**Comment by lazyfrosch** [comment]
I've seen a similar issue

Before:
- Jenkins 1.658
- Gitlab Plugin 1.1.28
- /builds URL _not_ working
- Builds on push and merge request opening works

After:
- Jenkins 2.2
- Gitlab Plugin 1.2.1 (tried to downgrade to 1.1.28 as well)
- No response to a merge request

I had to completely downgrade so it works again for me.

Are Matrix build so different to cause trouble here? I use it to test Puppet modules with different Puppet and Ruby versions.

**Comment by omehegan** [comment]
@lazyfrosch yes, Matrix builds IMO were never really a "first class citizen" inside Jenkins. I used them for years, but plugin support for them was always spotty. The basic problem is that, if you wanted to support them as a plugin author, you had to have special cases throughout your code. Whereas if you consider Freestyle, Pipeline, and Maven jobs as "first class" types, you can support all three by extending the Job and Run classes. That's often all you need. 

The /builds URL not working is due to the fact that it's supposed to respond to a request that passes the commit ref. In Matrix builds, the ref is used at the child/axis build level, rather than the parent/flyweight build level. So that whole aspect of the plugin would have to be refactored with a special case for Matrix.

That said, I am surprised that the trigger functionality broke. Given that downgrading the plugin did not restore that for you, I have to guess that something changed with Matrix support in Jenkins 2.2. I'm still using 1.651.2.

**Comment by omehegan** [comment]
@lazyfrosch I just realized something. You said when you upgraded the plugin, even the trigger stopped working. We have this issue open: https://github.com/jenkinsci/gitlab-plugin/issues/299  Maybe your jobs simply lost their configuration after you upgraded. If so, you should be able to upgrade and reconfigure the trigger, and at least that function would work.
