### ISSUE TITLE
Conditionally avoid to return the build status to gitlab merge request

### ISSUE THREAD

**Issue by fontealpina** [jenkinsci/gitlab-plugin#152]
In my workflow there is the need to avoid returning the build status to gitlab merge requests if a condition is verified, for instance if the job build status is 'aborted'.
Both build status on the top of the merge request and the comment in the comments list.
Can be added a new feature to the plugin to allow this? 
Thanks

**Comment by coder-hugo** [comment]
Skipping the build status update for aborted builds is impossible for GitLab 8.1+. Since GitLab 8.1 there is an API to notify GitLab about build status changes. This means:
1. the jenkins build starts -> tell GitLab a new build is running
2. the jenkins build ends
   - with success -> tell GitLab the build was successful
   - with failure -> tell GitLab the build failed
   - aborted -> tell GitLab the build was canceled

If the Jenkins doesn't notify GitLab about the status of a the currently running build this build remains forever in status running and as long as no new commit gets pushed to the MR the state of the MR will remain in the status running, too.
IMHO this should be changed on GitLab side so it will use the state of the last not canceled build as state for a MR.

Btw. can you be a bit more concrete about your conditions that need to be verified before adding the comment to a MR. This would be helpful to determine if this is useful for others, too and how can we implement this.
