### ISSUE TITLE
Remove source branch with "Accept merge request on success"

### ISSUE THREAD

**Issue by sebastienbonami** [jenkinsci/gitlab-plugin#181]
Hi, it would be nice to have the option to remove source branch automatically when the functionality "Accept merge request on success" is used in a Jenkins job.

Thanks!

**Comment by omorillo** [comment]
I'm on it.

**Comment by omorillo** [comment]
My implementation for this issue is now ready. 

Unfortunately, I observed a bug in the **GitLab API** implementation which results in the source branch always to be removed when using the _"Accept merge request on success"_ feature, no matter whether the **"should_remove_source_branch"** flag was enabled or not. I could observe this behaviour in **GitLab CE** version **8.7.3** and **8.7.6**.

Creating an issue on the **GitLab bug tracker** (https://gitlab.com/gitlab-org/gitlab-ce/issues/17992).

As the feature can not properly work at the moment, the changeset will not be added to the master yet. A pull request will be put in place which will be merged to master, once the issue on **GitLab** site is fixed.

**Comment by sebastienbonami** [comment]
Well... this feature is now present on GitLab's side so I don't need this anymore.
