### ISSUE TITLE
Add option to mark unstable builds as success in GitLab

### ISSUE THREAD

**Issue by salashnik** [jenkinsci/gitlab-plugin#190]
i think UNSTABLE is success...
May be You can add option for this

**Comment by dblessing** [comment]
Whether 'UNSTABLE' is success or fail really depends on the project. As I understand it, sometimes UNSTABLE can mean that the code compiled, but automated tests failed. In this case, UNSTABLE should result in a failure on the GitLab side. However, in some other cases that may not be desirable. If anything, it should be a configurable option.

**Comment by salashnik** [comment]
>  If anything, it should be a configurable option.

of course!

**Comment by sebastienbonami** [comment]
I just tried the latest version (1.2.5) of the plugin and I have a "Passed" status in GitLab when the build in Jenkins is "Unstable". Is is the expected behavior? In my case, I would like it to be "Failed" in GitLab.

EDIT: I just found out why, my post-build action to publish the build status was before another action that turn the status into "Unstable".

**Comment by herau** [comment]
agreed with @sebastienbonami
