### ISSUE TITLE
Gitlab link under Changes (in Jenkins) does not include repository name

### ISSUE THREAD

**Issue by lafraia** [jenkinsci/gitlab-plugin#196]
Gitlab needs repository name (provided under job configuration) to access correct URL. The gitlab plugin is using

```
<gitlab_url>/commits/<commit_id>
```

it should be

```
<gitlab_url>/<repository_name>/commits/<commit_id>
```

Gitlab logo plugin requests this info under job configuration. Input GitLab repository name is formatted with "<group name>/<repository name>" (ex. gitlab-org/gitlab-ce)

**Comment by ghost** [comment]
@lafraia 
The problem is partially solved in fetching branches functionality. As far as I can see plugin fetches all projects accessible for its GitLab user. Then compares repo url field and source repository url from job configuration to find matching one. This is how plugin figures out the project and project id. You can see it [here](https://github.com/jenkinsci/gitlab-plugin/blob/75ebe514eabcc174db97d030c96a957c334e1c43/src/main/java/com/dabsquared/gitlabjenkins/GitLabProjectBranchesService.java).

On the other hand, I use something like this to extract project id:

``` bash
PROJECT_ID=$(echo $gitlabSourceRepoName | sed "s/\//%2F/g")
```

I think that providing this info in configuration might make things easier.

**Comment by coder-hugo** [comment]
The gitlab link under changes gets generated by the jenkins git-plugin you have to select gitlab as repository browser and then you can enter the correct URL to your GitLab project.
