### ISSUE TITLE
Provide useful values of the Push and MR events as build variables

### ISSUE THREAD

**Issue by coder-hugo** [jenkinsci/gitlab-plugin#211]
Implement a BuildVariableContributor that provides values of the Push and MR events stored in the GitLabPushCause and the GitLabMergeCause as build variables. These variables should contain at least:
- gitlabBranch
- gitlabSourceBranch
- gitlabActionType
- gitlabUserName
- gitlabUserEmail
- gitlabSourceRepoHomepage
- gitlabSourceRepoName
- gitlabSourceRepoURL
- gitlabSourceRepoSshUrl
- gitlabSourceRepoHttpUrl

For MRs only
- gitlabMergeRequestTitle
- gitlabMergeRequestId
- gitlabMergeRequestAssignee
- gitlabTargetBranch
- gitlabTargetRepoName
- gitlabTargetRepoSshUrl
- gitlabTargetRepoHttpUrl

**Comment by klausbayrhammer** [comment]
this would be really really helpful!

**Comment by omehegan** [comment]
I'm trying to figure out how, after an MR is approved and merged, I can capture its ID in the subsequent build. I need this for change tracking purposes. Here is the workflow I envision:
1. User creates MR, there is discussion and eventually some +1's or whatever
2. User clicks 'merge' button, merge is successfully pushed to target branch
3. Push triggers a build, if build is successful we deploy to production
4. Because a deploy happened, I need to create a change management ticket, and I want it to have a reference to the MR so someone can see who gave approval

From what I can tell, however, when an MR is approved and merged, the only place the MR ID can be found is in the git commit message. I'd rather not have to parse that to find the ID I need. But perhaps this is a GitLab limitation. @dblessing do you have any comment on that?

**Comment by loran34** [comment]
Is it possible to add the description of the merge rquest too ?

**Comment by omehegan** [comment]
@dblessing wondering if you have any thoughts on my comment above. Seems like a GitLab question.
