### ISSUE TITLE
Add variable for global Merge request id

### ISSUE THREAD

**Issue by ghost** [jenkinsci/gitlab-plugin#246]
Add variable for global Merge request id.
now gitlabMergRequestId contains iId of git project.
For use gitlab API need variable with global id of git project

**Comment by pfrank13** [comment]
I don't know your exact use case but I needed a similar concept for the work I was doing, however the Gitlab API doesn't actually expose anything like this, in addition it seems like Git itself doesn't have a push as a first order concern, Git really seems to only deal with commits.  That being said the Gitlab API does provide a "before" and "after" hash that you can use to do things like find out all the hashes in a given push for a given branch.  I've entered an issue here #257 and have submitted a pull request that actually implements exposing a "gitlabBefore" and "gitlabAfter" in this pull request #258.  Don't know if that helps but your problem seems very close to mine.

**Comment by ghost** [comment]
Use case is very simple
I need to add comment for merge request after execution of another Jenkins job using gitlab API
For this purpose gitlabMergeRequestId can't be used, because it contains Iid instead of Id of merge request.

There two ways to use gitlab API for add comments 
1. Replace IId with id of merge request for gitlabMergeRequestId
2. Add new parameter gitlabGobalMergeRequestId with Id of merge request

**Comment by pfrank13** [comment]
Oh apologies I thought you were looking for a unique push id, your use case was very different from mine haha.  Oops =)

**Comment by omehegan** [comment]
@AceOfSnakes can you give an example of what you're looking for? I don't understand what the global ID is or how it is different from gitlabMergeRequestId. This may be something that needs to change on the GitLab side, if this isn't something they send in the hook JSON. Or else we would have to make additional API calls to get it maybe.

**Comment by ghost** [comment]
@omehegan 
http://doc.gitlab.com/ce/api/

> id vs iid
> 
> When you work with the API, you may notice two similar fields in API entities: id and iid. The main difference between them is scope.
> 
> For example, an issue might have id: 46 and iid: 5.
> 
> Parameter Description
> id    Is unique across all issues and is used for any API call
> iid   Is unique only in scope of a single project. When you browse issues or merge requests with the Web UI, you see the iid
> That means that if you want to get an issue via the API you should use the id:
> 
> GET /projects/42/issues/:id
> On the other hand, if you want to create a link to a web page you should use the iid:
> 
> GET /projects/42/issues/:iid

**id    Is unique across all issues and is used for any API call**
