### ISSUE TITLE
Configuration clarification

### ISSUE THREAD

**Issue by rigoford** [jenkinsci/gitlab-plugin#253]
More of a query than an issue, but...

I'm using GitLab CE 8.5.8 and Jenkins 1.642.2, with the Gitlab Plugin 1.1.31 (and required dependencies) installed. I've successfully configured a GitLab project to trigger a build on Jenkins, however I have quite a specific use case that I can quite seem to get working.

Given a GitLab project (example-project, with protected master branch) and two associated Jenkins jobs (example-project_REVIEW and example-project_CI), I want to trigger the Jenkins jobs based on the following events:
- All change sets pushed to a 'feature' branch should trigger the example-project_REVIEW job
- When any 'feature' branch merge requests are **accepted** (and only when they are **accepted**) they should trigger the example-project_CI job

The reason for this is the _CI job will do some extra stuff and push an atomic version of the deployment artefact to Nexus.

I hope that makes sense. I've followed (and experimented with) the config options on the README but can't get it quite right. Am I missing something obvious in the job config? Any suggestions welcome.

Thanks

Martin

**Comment by omehegan** [comment]
You should use Jenkins Workflow/Pipeline. Then you can just have one job, and put a conditional in the job based on the branch name. Much cleaner and more flexible than two separate jobs IMO. This is how we accomplish your goal. Otherwise, I don't think there is a way to have GitLab trigger different jobs depending on the branch, and this is a GitLab problem, not a plugin problem.

**Comment by smithrs** [comment]
I have it working that way. One job runs unit tests on the merge request using the source branch, the other does the full CI build against the master branch. Here's my recipe: 

Two builds which I will call MR build and CI build.
The MR build runs against the MR source branch and the CI build runs against the target branch which is master in our setup.

The Gitlab web hook for MR should include both push events and MR events.
The Gitlab web hook for CI build should only include push events.

Set up Jenkins MR build so that build on MR events is checked but build on push is not checked.
Set up Jenkins CI build so that build on MR events is not checked but build on push events is checked.

Set up MR build to allow all branches.
Set up CI build to only allow master.

If you are not using master as your target branch you'll have to use regexes to get the behavior you want.

MR build should also be doing the merge before build as stated in the documentation, and you must also make sure the build user sets git user.name and user.email before SCM actions take place.

Make sure Jenkins user (the API user token that pushes from Jenkins to Gitlab) is a Developer on your project and that the project has "Developers can push" enabled on the integration branch if you are using protected branches and you want the auto-merging behavior to work.

Last, I strongly recommend you set up a separate VM for testing all this stuff if you haven't done so already.

**Comment by rigoford** [comment]
Thanks for your prompt responses. I like the idea of using Pipeline, it should be the most flexible option. However, setting up a simple Pipeline Jenkins job and attempting to trigger it from a GitLab Webhook (using Test Webhook) I get an immediate error along the lines of "java.lang.IllegalArgumentException: This project does not use git:my-new-project_GITLAB".

I've got Pipeline (1.14) installed, but I know my GitLab (CE 8.5.8) / Jenkins (1.642.2) setup is okay since non-pipeline Jenkins jobs can be triggered from a GitLab Webhook.

I assume that the failure is due to the fact that I have not (cannot, since there is no SCM option) specified the source repo. What am I missing @omehegan?

**Comment by rigoford** [comment]
It appears that I have to use two Jenkins jobs, the first is a freestyle project (with the necessary SCM section config) and is called by the GitLab Webhook. The second is a Pipeline and contains a Groovy script that contains the necessary logic to determine whether to do a REVIEW or a CI build.

This approach seems a bit cumbersome, but looks like it'll work. Unless I've got hold of the wrong end of the stick?

**Comment by omehegan** [comment]
@rigoford sorry for the delay in response.

Your Pipeline job's script should have a step in it which checks out your code from git. This would be distinct from the trigger configuration of the job, where you indicate that the job will be kicked off by GitLab hooks.

Then, because of a "feature" of the plugin, you will need to run the job manually once, and have it succeed, before the plugin will work. This is why you are getting the "java.lang.IllegalArgumentException: This project does not use git:my-new-project_GITLAB" error. You will need to hard-code a value for branch and any other parameters you use in the job which the GitLab hook would otherwise populate, or create parameters for them with valid defaults. We will be fixing this "feature" (bug) in the near future.

This should allow you to do everything in one Pipeline job. Let me know if this is unclear or you have other issues.

**Comment by rigoford** [comment]
@omehegan thanks for the response, no worries about the delay - I've been occupied for the past couple of weeks.

So the pipeline job I have doesn't have an option to configure any steps (unless you mean I should create a stage in the pipeline script).

The requirement to run the job manually once is also a bit of a problem for me since the creation of the GitLab project and the associated Jenkins jobs is automated (an developer just give a project name and description to a Jenkins job and everything is created for them) - although if you're gonna fix that feature that's cool.

I really don't see how I can do everything in one pipeline job - clearly I'm missing something.

**Comment by omehegan** [comment]
@rigoford install the latest version of the plugin. This fixes the need for a manual run before things will work. Then, look at the readme for instructions on configuring a Pipeline job. It all works now.
