### ISSUE TITLE
Support [WIP] tag to prevent builds from triggering

### ISSUE THREAD

**Issue by cotman** [jenkinsci/gitlab-plugin#261]
Hi,

Is this possible?

I know there's the `[ci-skip]` option in commit messages, but that kind of pollutes the commit message history.

The use case is a Jenkins job that's configured to respond to MR events and push events to the source branch of the MR.  In most cases, this is fine.  However, there are situations when a speculative MR is opened just to make work visible in a diff as it's on-going - this doesn't really require builds to run until it's complete, and may get very many pushes that are known to not have a chance of passing until it's complete.

What would be ideal, for the above, is if there were the option to _not_ build jobs from Gitlab triggers if the standard `[WIP]` were in the MR title, maybe, or `[SKIP-CI]` at the MR title/comment level?

Is something like that possible now, without changing the config of the job so that it operates for "normal" triggering?

Thanks.

**Comment by omehegan** [comment]
Oh, I thought the ci-skip tag was supposed to be used in the MR title, not in commit messages. But I didn't write that feature. I'll check this out and maybe make a change to support the [WIP] syntax. I do have a vague memory that GitLab supports something on its side where you can tell it not to trigger hooks if the MR is labeled a certain way...

**Comment by omehegan** [comment]
@cotman in fact, it's as I remembered: if you put [ci-skip] in the MR title, and check that box in the Jenkins job config, the job will not trigger on updates to the MR. You can remove [ci-skip] when you are ready to allow triggering. If that does not work for you, please let me know.

I will add a note that we should also support [WIP] because that seems to be a common pattern.

**Comment by cotman** [comment]
Oh - nice - thanks.  I'd just assumed that [ci-skip] was only usable in commits from what I had found searching about.  Will try in the MR title and see if it works for us and will update this issue.

**Comment by eskobarba** [comment]
+1 for WIP in the MR title

**Comment by TheStormN** [comment]
+1 for WIP. Also bare in mind that the WIP tag have several possible syntaxes - WIP, [WIP], and maybe some more.

My proposal is to use the JSON variable **work_in_progress** that transmitted with the hook. This way you will not have the burden to parse the MR title and it sounds much more compatible.

**Comment by ValerioCadeddu** [comment]
Hi @omehegan , I was reading this issue since I have a question about the use of WIP checkbox on Jenkins pipeline.
I need to resolve a thing, basically, I have two pipelines that are triggered both by MR events on gitLab. Our process is, Open a MR directly with WIP text in the title box, and enable the pipeline A to be triggered since the WIP checkbox is unchecked. At the same time, the pipeline B has this checkbox checked, so it is not triggered. At this point all is fine, but I want to exclude a triggering that happens when I edit the MR, deleting from the MR title the string WIP. How can I avoid this additional triggering of pipeline A?
Now when I change the MR title, both pipelines are triggered. Thanks a lot Valerio

**Comment by omehegan** [comment]
@ValerioCadeddu this is because edits to the MR like that trigger a new webhook event from GitLab.

**Comment by yeikel** [comment]
Is there anything like this for Bitbucket or Github?
