### ISSUE TITLE
Wrong GitLab Merge Request ID

### ISSUE THREAD

**Issue by tnucera** [jenkinsci/gitlab-plugin#290]
Hello,

Jenkins 2.1
Git plugin 2.4.4
GitLab plugin 1.2.1

The merge request ID displayed is wrong.

```
"object_attributes" : {
    "id" : 1856,
    "target_branch" : "master",
    "source_branch" : "master",
    "source_project_id" : 189,
    "author_id" : 22,
    "assignee_id" : 22,
    "title" : "tests",
    "created_at" : "2016-05-03 15:39:32 UTC",
    "updated_at" : "2016-05-03 16:08:21 UTC",
    "milestone_id" : null,
    "state" : "closed",
    "merge_status" : "can_be_merged",
    "target_project_id" : 131,
    "iid" : 137,
```

The good value is "iid".

I currently testing your plugin and another.
Is it possible to have the forked repository name with the URL to GitLab like this?
Thank you for ur plugin!

![capture d ecran 2016-05-03 a 18 28 34](https://cloud.githubusercontent.com/assets/10210667/14990685/013c848c-115e-11e6-8fa6-76e7763a149c.png)

**Comment by coder-hugo** [comment]
For using the gitlab API the "id" is the good value :wink: If the "iid" is also required we should add this as an additional variable called gitlabMergeRequestIid.

**Comment by omehegan** [comment]
@aceofsnakes requested this as a separate variable in https://github.com/jenkinsci/gitlab-plugin/issues/246

**Comment by coder-hugo** [comment]
@omehegan @tnucera now I see the real issue with the ID. Within the build description the plugin shows currently the wrong id. I'll fix this ASAP.

**Comment by petewilcock** [comment]
@coder-hugo Can we re-open this? I see this issue too with latest plugin and Gitlab ee. 

You say 'gitlabMergeRequestId is the correct one for the gitlap API', but I don't think so. I cannot do a checkout on `refs/merge-requests/${env.gitlabMergeRequestId}/head` because this PR number does not exist. `${env.gitlabMergeRequestIid}` is the correct number. If I modify my pipeline to use this value instead, it works perfectly. 

This is confusing and if it is the intended behaviour it needs better documentation? The build description used Iid and is correct.

**Comment by omehegan** [comment]
@petewilcock can you open a new issue about this? It's probably not directly related to this original thing, just the same behavior. Also FWIW @coder-hugo is no longer working on this plugin.

**Comment by rmaheo** [comment]
I have same problem since 26 july. @petewilcock do you have this issue yet ? If yes, did you create a new issue about this subject ? (I didn't find it, probably I'll create one).

**Comment by petewilcock** [comment]
@rebecamaheo Apologies, I hadn't created one. Please do :)
