### ISSUE TITLE
Gitlab namespace not present in gitlabSourceRepoName

### ISSUE THREAD

**Issue by smithrs** [jenkinsci/gitlab-plugin#316]
Prior to 1.2, the variable `gitlabSourceRepoName` was populated with namespace/repo-name, the same as the json variable `[project][path_with_namespace]` passed in from the web hook.

With 1.2, it only contains the repo-name. I know the 1.2 plugin has new variables, but it shouldn't break backward compatibility with the variables that were present prior to 1.2.

Am I the only one seeing this? There are several API calls back into Gitlab that break if you don't have a namespace value to pass in.

**Comment by cgumpert** [comment]
I see the same problem. Unfortunately, this break my script to add custom comments to a merge request. One could probably work around this, but I agree. It would be nice to have the namespace information available.

**Comment by omehegan** [comment]
The variable `gitlabSourceNamespace` now contains the namespace. This is in keeping with an effort to populate variables with information as sent directly from GitLab, rather than making up our own idea of what they should contain. Sorry for the breakage!

BTW, the [project] key in the GitLab JSON was not added until GitLab 8.5. It can be a challenge for us to maintain backwards compatibility while also tracking changes to GitLab.
