### ISSUE TITLE
Provide Build Trigger when hooks are not an option

### ISSUE THREAD

**Issue by pazoozooCH** [jenkinsci/gitlab-plugin#346]
### Context
- **Gitlab plugin version**: 1.2.3
- **Gitlab version**: 8.8.3
- **Jenkins version**: 1.651.2
### Problem description

I have an environment where Jenkins is inside a corporate LAN and Gitlab is on public internet without access to Jenkins. That means I cannot have any notifying post commit hooks to trigger anything on Jenkins, but must rely on polling to trigger my builds.

Apparently, that is not supported by gitlab-plugin or am I missing something? The similar gitlab-merge-request-builder-plugin (https://wiki.jenkins-ci.org/display/JENKINS/Gitlab+Merge+Request+Builder+Plugin) would provide a build trigger plugin that would check for changes on Gitlab by a Jenkins Timer, e.g. every 5 minutes (configurable cron style).

With the latest version updates, the gitlab-merge-request-builder-plugin stopped working for me and I would be happy to move to the gitlab-plugin. Can you think of any workaround for my problem or is this a missing feature that somebody might want to add?

Thanks Martin

**Comment by omehegan** [comment]
You can just configure polling using either the Poll SCM or Build Periodically options within the job configuration. That isn't unique to this or the merge request builder plugin. That's probably the only way this will work for you. Then I think you should be able to add a post-build step which sends the build result to GitLab.

**Comment by pazoozooCH** [comment]
Thanks for the feedback. I doubt that this will work reliably. The problem is that pushing changes and creating a merge request are two distinct actions. I might push a change now but open the merge request 2 hours later. In such a case, the period build will already have been triggered, not finding a new merge request.

For now, I have addressed the problem by moving the related merge request build job to a new Jenkins that has the required connectivity...

**Comment by coder-hugo** [comment]
Implementing a polling mechanism to get "notified" about Push or MR events isn't a good idea for several reasons:
1. Periodic polling of the open MRs will slow down the GitLab
2. Depending on the amount of open MRs the API call can take several seconds which blocks resources on your Jenkins. Depending on the number of jobs doing this polling this will slow down your Jenkins as well.
3. You need to store a lot of unnecessary data for each build just to be able to determine if there was a change for a MR.
4. You can't remove historical build data otherwise the plugin will "rebuild" a MR if the last build for this MR is removed.
5. With 3. and 4. in mind the process of getting "notified" about MR events will become slower over the time as all builds have to be checked if the found MR is a new one or and old that has been changed.

The only way for using the full functionality of this plugin is to setup your Jenkins (including network stuff) to be able to receive the events from GitLab.

**Comment by pazoozooCH** [comment]
@coder-hugo, thanks for the feedback. I've already "solved" the issue for me by moving to another Jenkins that can be reached by the Gitlab host.
