### ISSUE TITLE
gitlab test jenkins webhook return 404

### ISSUE THREAD

**Issue by lazywhite** [jenkinsci/gitlab-plugin#354]
### Software Versions

gitlab: 8.3
jenkins: 2.8
jenkins-gitlab-plugin: 1.2.3
### Configs

repo_address: http://gitlab.xxx.com/white/jenkins_test.git
webhook: http://x.x.x.x:5000/project/jenkins_test
### Logs

```
Jun 12, 2016 4:14:44 PM com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
INFO: WebHook called with url: /project/jenkins_test
```
### problem

I configured a jenkins job and can execute it manually, but webhook always return 404

**Comment by omorillo** [comment]
Have you set the **webhook** url as suggested in the jenkins job? You may also have a typo in the url.

**Comment by djdevin** [comment]
I also get a 404, after upgrading, from a working installation.

```
GET https://mydomain.com/project/Test_BRANCH
404 Not Found
```

GitLab 8.8.1-ee
jenkins: 2.8
jenkins-gitlab-plugin: 1.2.3

**Comment by omehegan** [comment]
I wonder if this is a Jenkins 2.8 issue. Can you both check the main Jenkins log, rather than the plugin-specific log, and see if there are any errors logged there?

**Comment by lazywhite** [comment]
I'm sorry, I didn't configure the webhook rightly,  PROJECT_NAME should be jenkins job name , not gitlab project name.

**Comment by omorillo** [comment]
@lazywhite Great to hear, that it fixed your issue.

**Comment by omorillo** [comment]
@djdevin Just to be sure I understand correctly. You upgraded the _gitlab plugin_, didn't you?

**Comment by djdevin** [comment]
@omorillo I did, that's actually why it broke. I missed the switchover to the Credentials system, so reinputting the API key based on the readme fixes it.

**Comment by omorillo** [comment]
Great!

**Comment by bert2002** [comment]
Hi,

i am running into the same problem. I added the credentials based on the readme (secret text) and the connection test is working, but every call to https://mydomain.com/project/JENKINS_JOB_NAME results in a 404 on the jenkins server.

The only difference is that i run jenkins: 2.10

Any other idea?

**Comment by coder-hugo** [comment]
@bert2002 to figure out what's happening it would be helpful to have some logs. Please have a look to the [user support](https://github.com/jenkinsci/gitlab-plugin#user-support) section how to enable logging for the GitLab plugin.

**Comment by bert2002** [comment]
I found a workaround. I downgraded the gitlap-plugin to 1.1.32. I know thats not a solution, but at least its working now.

**Comment by vmaurin** [comment]
@bert2002 
I had the same issue and for me it was from a 302 returned by my jenkins server.
Let me explain the flow : 
- Gitlab send a POST to the jenkins server to the configured URL (starting with http:// in my case)
- My jenkins server working with https send a 302 redirect to the same url, but starting with https://
- Then Gitlab follows the redirect, but send a GET query, that is rejected by the GitLab plugin

So in my case, the fix was just to configure directly the link starting with https in gitlab, and then avoiding the redirect

I have submitted an issue to gitlab https://gitlab.com/gitlab-org/gitlab-ce/issues/19696

**Comment by RyanYans** [comment]
I found that the WebhooksURL can not be "localhost" or "127.0.0.1", please find your IPv4 address.

**Comment by omehegan** [comment]
@RyanYans that is caused by #730, you can change a setting in GitLab to fix it.

**Comment by panostzemis** [comment]
First of all have a look o Jenkins logs in order to check if it receives the Hook.
You should see something like this 
> INFO: WebHook called with url: /ci/project/content-fetch

In case you are accessing your Jenkins/Git with **HTTP**, add your webhook as provided by Jenkins on project  settings
`http://domain/ci/project/<project-name>`

and uncheck 
`Enable SSL verification`

In case you have **HTTPS**
Use your Jenkins project URL but this time add **https** instead of **http**``

`https://domain/ci/project/<project-name>`
And check
`Enable SSL verification`

Also on Jenkins project configuration on **Build Triggers/Build when a change is pushed to GitLab.**
by pressing the advanced button you will find **Generate Code**
Generate a code and insert it on the GitLab Webhook settings.
 
That should work for you.

**Comment by ashokmahato** [comment]
Dear experts, 
I am facing same issue http 404 .
Checked below things
1.Jenkins Userid is correct 
2.Api token generated from that Jenkins user
3. Enable authentication for '/project's end point : unchecked 
Webhooks url:  https//Userid:apikoken@jenkinsServerurl/project/job-name

Please help/suggest .

**Comment by ricardo-aspira** [comment]
Any news on that? I am facing the same issue.

**Comment by patrickjeried** [comment]
any updates?

**Comment by sdklab007** [comment]
I am facing the same. Did anyone find the solution?
