### ISSUE TITLE
"Parametrized builds" section of README is out of date

### ISSUE THREAD

**Issue by vstriz** [jenkinsci/gitlab-plugin#356]
### Context
- **Gitlab plugin version**: 1.2.3
- **Gitlab version**: 8.8.3
- **Jenkins version**: 2.8
### Problem description

I had some trouble upgrading to latest versions of everything. Specifically with variables/parameters being passed to the plugin. I understood that instead of parameters they now got passed as env variables, but it looked like some of them where empty. I did read the linked pages on jenkins security update and EnvInject plugin but it wasn't clear what's going on.

I finally figured out that you have to REMOVE the parameters. and make your merge-request job be un-parametrized. Any parameter specified (E.g. gitlabTargetBranch) caused the corresponding env variable to NOT get populated. Remove all parameters fixed the problem.

So my only complaint that this wasn't clear from README and that "Parametrized builds" section still suggests making parameters which won't work now with latest jenkins/plugin

**Comment by omorillo** [comment]
You are totally right about the lack of information in the _README_, @vstriz. We already discussed with @omehegan about adding more information regarding this topic to the _README_ among others how to use the [EnvInjPlugin](https://wiki.jenkins-ci.org/display/JENKINS/EnvInject+Plugin) to overcome this issue.

I will take care of it as soon as possible to avoid misunderstanding to other users!

But for you to fully understand how it is expected to work, below a little explanation:

You usually have two scenarios:
1. You want automate triggering on push / merge event.
2. You want to manually trigger a job.

In case of the first scenario, the parameters which are listed in the [Parameterized builds](https://github.com/jenkinsci/gitlab-plugin#parameterized-builds) section are automatically injected by the plugin, so that you do not need to take any action there.

In the latter case, you may use the above-mentioned plugin to manually set the desired parameters before any manual triggering.

**But how to do this?**
To this end, you specify some variables through the [Parameterized Trigger plugin](https://wiki.jenkins-ci.org/display/JENKINS/Parameterized+Trigger+Plugin) with unreserved names e.g. "SourceBranch" and "TargetBranch" (but not _"gitlabSourceBranch"_ or _"gitlabTargetBranch"_ which are reserved by the plugin) and you can check in the _EnvInjectPlugin_ "EvaluateScript" text area if the variables (_gitlabSourceBranch_ and _gitlabTargetBranch_) provided by the plugin are filled, if so you can override your own defined variables.

In any place where you would use _gitlabSourceBranch_ and _gitlabTargetBranch_ you would use your own variables then.

The check must look like something like that:

``` groovy
// overrides the value in "SourceBranch" when gitlabSourceBranch is set
if (binding.variables.containsKey('gitlabSourceBranch')) {
    return [SourceBranch: "$gitlabSourceBranch"]
}

// overrides the value in "TargetBranch" when gitlabTargetBranch is set
if (binding.variables.containsKey('gitlabTargetBranch')) {
    return [TargetBranch: "$gitlabTargetBranch"]
}
```

**Comment by omorillo** [comment]
**Note that you can define such own variable for each of the existing reserved parameters defined in the parameterized build section**

**Comment by vstriz** [comment]
Right, that's exactly what my problem was. I didn't realize that you could no longer use the parameter names exactly as they used to be. e.g. gitlabSourceBranch. And unfortunately there was no clear explanation anywhere. Your message above is actually perfect. Would have saved me a few hours :)

**Comment by omorillo** [comment]
Hope it will save at least for others! ;) Thanks for your contribution.

**Comment by omehegan** [comment]
@omorillo are you going to update the documentation for this? I don't think you need to use Parameterized Trigger to get manual builds to work. As long as you created parameters in the job config that _are not_ the same as the env vars the plugin will create, you should be able to write the necessary values to that when a manual build is run.

**Comment by omehegan** [comment]
@omorillo also see the comments here: https://issues.jenkins-ci.org/browse/JENKINS-34700

**Comment by omorillo** [comment]
@omehegan Yes, I am about to update the documentation. 

And yes, you are right it suffices to have some interface to provide variables with values which can be passed to the git plugin. I just mentioned the parameterized trigger as example. But actually I was referring to the [Parameterized build](https://wiki.jenkins-ci.org/display/JENKINS/Parameterized+Build) plugin.

Thanks for the link to the Jenkins issue _34700_, will consider it when extending the _README_.

**Comment by razzeee** [comment]
Thanks @vstriz for letting us know how to fix it, I just had the same problem

**Comment by rocklan** [comment]
Thanks @vstriz for the fix - this one has been driving me nuts all day.

**Comment by rocklan** [comment]
@vstriz Is there a different fix for this? I tried going down the groovy script path but it didn't work for me, any ideas? Or @Razzeee  ?

**Comment by razzeee** [comment]
I just deactivated parametized build for the job and that fixed it. Not sure what the groovy script path is

**Comment by ElijahLynn** [comment]
I don't see the documentation updated for this here https://github.com/jenkinsci/gitlab-plugin/blob/master/README.md. Is that the right location to expect documentation for this and am I missing it?

**Comment by ElijahLynn** [comment]
@omorillo ^^

**Comment by ElijahLynn** [comment]
K, I got it working with "Prepare an environment for the run", checked "Keep Jenkins Environment Variables", "Keep Jenkins Build Variables" and "Override Build Parameters" where the last one was key to getting it working. 

Jenkins 2.114
gitlab-plugin 1.5.5

```
import hudson.model.*
def env = Thread.currentThread()?.executable.parent.builds[0].properties.get('envVars')
def map = [:]

if (env['gitlabSourceBranch'] != null) { 
  map['SourceBranch'] = env['gitlabSourceBranch'] 
}
if (env['gitlabTargetBranch'] != null) { 
  map['TargetBranch'] = env['gitlabTargetBranch'] 
}

return map
```


![image](https://user-images.githubusercontent.com/1504756/39460648-21a9ccc2-4cd3-11e8-8cbd-186d7e98e689.png)

**Comment by omehegan** [comment]
@ElijahLynn the documentation never got updated for this, so thanks for your solution. I will use it as the basis for that update. Just to clarify, in your example, does your job have two parameters defined, named SourceBranch and TargetBranch? Or how are you using the map that you created?

**Comment by ElijahLynn** [comment]
Yes, it does have two parameters defined, and technically they should probably be the proper case which is `sourceBranch` and `targetBranch`. One downfall of this approach is that when a build is queued and we hover over to see the incoming parameters they are the defaults set in Jenkins, not the incoming source/target branch that GitLab is sending us. So I still need to figure out a solution to that because not seeing that information has already caused some team members some frustration.

**Comment by omehegan** [comment]
Fixed in the current version of the README.

**Comment by ElijahLynn** [comment]
Thanks. 

aa8c1011b88d5b33c0f689b6ce257257b58acfaa
