### ISSUE TITLE
Readme does not mirror correctly the setup for GitLab 8.8

### ISSUE THREAD

**Issue by omorillo** [jenkinsci/gitlab-plugin#360]
In **GitLab 8.8** we do not have to enable the _GitLab CI_ any more as it is required for older _GitLab versions) (see _README_). This change is currently not explained in the [README](https://github.com/jenkinsci/gitlab-plugin/blob/master/README.md).

We need to identify which **GitLab** version introduced this change and need to update the _README_ to include this information together with the identified version.

**Comment by coder-hugo** [comment]
@omorillo I'd say it isn't required since version 8.1 of GitLab to enable the GitLab CI. I just tested it with the current version of the plugin and a dockerized GitLab 8.1
But nevertheless the documentation for the GitLab configuration >= 8.1 isn't correct. As the plugin uses since version 1.2 the MR hook instead of the push hook the rebuild open MRs it's not necessary to configure the Web Hooks for forked repositories.
