### ISSUE TITLE
getCommit has void return in com\dabsquared\gitlabjenkins\gitlab\api\GitLabApi.class

### ISSUE THREAD

**Issue by deverin** [jenkinsci/gitlab-plugin#363]
I am using Groovy post build in jenkins and I am trying to get a Commit but get a null back.

Why if it is a @GET request method is not returning proper type?

Maybe it is not an issue but all other @GET method are properly returning correct types.

method in the contract

``` java
  @GET
  @Produces({"application/json"})
  @Path("/projects/{projectId}/repository/branches")
  public abstract List<Branch> getBranches(@PathParam("projectId") String paramString);
```

GitLabApi type is exposed in jenkins in Groovy Postbuild step like this

``` groovy
def gitLabApi = manager.build.getParent().getProperty("com.dabsquared.gitlabjenkins.connection.GitLabConnectionProperty").getClient()
```

then calling `gitLabApi.getCommit("somProjectName", "4fp54")` will give null

Maybe I am not aware of something but how is it possible to get out this JSON response from void method?

**Comment by coder-hugo** [comment]
We need this method of the GitLab API just to determine if a commit exists or not. For this we just need to evaluate the HTTP status code. So usually a HTTP HEAD would be enough but we can't do this due to the following [bug](https://issues.jboss.org/browse/RESTEASY-1347) in RESTEasy.
Furthermore I wouldn't suggest you using this class in your groovy script as this is not part of "the pulblic API" of the plugin and could be changed with one of the next releases and break you job.
