### ISSUE TITLE
Unclear documentation with new interface

### ISSUE THREAD

**Issue by namnn96** [jenkinsci/gitlab-plugin#391]
Hi team,

I believe GitLab has changed much regarding the documentation and Jenkins' documentation is poorly written, which confuse me quite a bit.

I am trying to trigger a jenkins build on my local with GitLab push. Following what I have googled, I have:

____GitLab____
- Gone to Services > Jenkins
- Ticked the Active box and Push box

____Jenkins____
- In Manage Jenkins > Configure, I filled in Gitlab information (connection name, host url, credentials)
  - Jenkins Location (Jenkins url)
  - GitLab Account Setting (endpoint url, private token)
- In Job's configure
  - Source Code Management > Git (repo url, credentials, branch)
  - Build trigger

When I test settings in gitlab, I got an error "Execution expired".
My question are:
1.  What exactly I need to put into the Jenkins url field? Is that the link to the Jenkins itself, or direct link to the job?
2.  Under Project name, is that compulsory to be the same as the project name in jenkins, or it is any name that I can think of?
3.  Are the Username and Password the ones I use for Jenkins login?
4.  Last but not list, what exactly I need to config in Jenkins fot GitLab trigger? There are too many fields with no clear explaination.

Thanks in advance.

**Comment by coder-hugo** [comment]
At the moment I have no possibility to use GitLab EE so I can't tell whether the UI has changed much regarding the documentation or not. I also noticed that our documentation could be improved. But due to the lack of time this has not happened yet. Maybe we should move parts of the documentation to the wiki where we can structure them more easily.
Now to your 4 questions:
1. Enter the URL to your Jenkins.
2. Enter the name of the Jenkins job/project (ensure the name is URL friendly so it shouldn't contain whitespaces)
3. These are the credentials that GitLab required to interact with your Jenkins if you have enabled authentication for the /project endpoint in the GitLab section of the Jenkins global configuration.
4. I think the names of the available options are pretty straight forward, just select the ones that fit your needs.

**Comment by LongLiveCHIEF** [comment]
> 1. I think the names of the available options are pretty straight forward, just select the ones that fit your needs.

I don't think is as straight forward.  Questions I have: 

Why do my jobs need to enter a credential for gitlab if I have configured the gitlab plugin globally in jenkins? (what additional things does configuring Jenkins Gitlab Plugin globally provide?)

> ____Jenkins____
> 
> In Manage Jenkins > Configure, I filled in Gitlab information (connection name, host url, credentials)
> Jenkins Location (Jenkins url)

What is this "jenkins url" we speak of, and why are we putting a jenkins url inside of a jenkins configuration? I don't have any such option in Jenkins, either 1.x or 2.x versions.

**Comment by coder-hugo** [comment]
> I don't think is as straight forward. Questions I have:
> 
> Why do my jobs need to enter a credential for gitlab if I have configured the gitlab plugin globally in jenkins? (what additional things does configuring Jenkins Gitlab Plugin globally provide?)

The globally configured credentials are just for using the GitLab API to update the commit status or get some information about MRs, they can't be used for cloning repositories.

> What is this "jenkins url" we speak of, and why are we putting a jenkins url inside of a jenkins configuration? I don't have any such option in Jenkins, either 1.x or 2.x versions.

This plugin doesn't ask for a Jenkins URL this is part of the Jenkins itself.

**Comment by LongLiveCHIEF** [comment]
> In Manage Jenkins > Configure, I filled in Gitlab information (connection name, host url, credentials)
> Jenkins Location (Jenkins url)

**Comment by omehegan** [comment]
@LongLiveCHIEF are you still having issues triggering builds from GitLab?

**Comment by LongLiveCHIEF** [comment]
Nope!
