### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by iamsamuelfraga** [jenkinsci/gitlab-plugin#453]
## Issue

Failed to connect to repository : Command "git ls-remote -h git@gitlab.com:****/****.git HEAD" returned status code 128:
stdout: 
stderr: Host key verification failed. 
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

### Context
- **Gitlab plugin version**: 1.4.3
- **Jenkins version**: 2.19.3
- **Gitlab server**: https://gitlab.com/

### Problem description

I want to connect my Jenkins server to a remote Gitlab repository hosted on https://gitlab.com. I configure all as [this link](https://github.com/jenkinsci/gitlab-plugin#configuring-access-to-gitlab) but on step _ii. Enter your Repository URL (e.g.: git@your.gitlab.server:group/repo_name.git)_ shows me this error:

Failed to connect to repository : Command "git ls-remote -h git@gitlab.com:****/****.git HEAD" returned status code 128:
stdout: 
stderr: Host key verification failed. 
fatal: Could not read from remote repository.

I have configured the Gitlab Connection as follows:
![gitlab-connection](https://cloud.githubusercontent.com/assets/15862787/20636527/d4fe24bc-b36e-11e6-9be8-c95eed427f21.png)

and when I test connection the result is SUCCESS.

Please help!

**Comment by omehegan** [comment]
The problem you are encountering is due to a problem with the Git plugin, not the GitLab plugin. The Git plugin is unable to clone the repo you have specified, because it does not have permission to do so. You need to generate an SSH key and add it Jenkins (the easiest place to do this is in your job configuration if it's a Freestyle job) and to a user in GitLab, and the user in GitLab must have access to clone to the repo.

Once again, this is NOT an issue with the GitLab plugin.
