### ISSUE TITLE
When pipeline job is pending, no build status show on gitlab mr

### ISSUE THREAD

**Issue by GeneralMaple** [jenkinsci/gitlab-plugin#474]
I what to check MR  before merging it . I use gitlab pipeline in jenkins. But when pipeline is pending, no build status is shown on gitlab for the merge request. How to solve this? I want show a build  immediately when  web hook has been triggerd or the mr can be merged before my jenkins job is executed.

**Comment by omehegan** [comment]
Do you mean you want GitLab to know that a build is pending in Jenkins before that build has started? If so, that is not possible.

**Comment by GeneralMaple** [comment]
@omehegan Yeah, that is what I want. because I set 'only can be merged when build success' in gitlab, so if  Gitlab don't know the build is pending  when a mr has been made. then every mr can be merged without mr build check.

You said it is not possible. but why freestyle job can do this ? Using freestyle job, when a mr has been opened , gitlab shows pending build state right away even jenkins job related to that mr  is pending.

**Comment by omehegan** [comment]
I have a feeling that Pipeline jobs treat the status of "pending" or "queued" differently from Freestyle jobs, but I am waiting to confirm.

However, your issue sounds like a potential bug with GitLab. If you are describing this scenario:
1. GitLab should only allow an MR to be merged if the Jenkins build succeeds
2. You create an MR and it triggers a Jenkins Pipeline job build which goes into the build queue (due to no available executors in Jenkins)
3. GitLab will allow that MR to be merged even though the build has not run yet

Then I think that is a GitLab bug. It clearly has not received a status result from Jenkins, so it should not allow the merge, regardless of what other state the Jenkins job is in.

Some additional information about what versions of GitLab, Jenkins, and our plugin you are using (as requested in the new issue template) would help here.

**Comment by omehegan** [comment]
@YanceyWang can you respond to my last comment, in the sense that I don't think GitLab should behave the way you are describing? I need to make sure I really understand the behavior you are seeing.

**Comment by jgeorgeson** [comment]
It's not so much a bug in GitLab as a poorly worded description of the setting. I have an issue open with them \[[link](https://gitlab.com/gitlab-org/gitlab-ce/issues/24495)\] to provide an option to require a build rather than the lack of a failed build.

**Comment by matil019** [comment]
@omehegan @YanceyWang

Hello,

> Do you mean you want GitLab to know that a build is pending in Jenkins before that build has started? If so, that is not possible.

I happened to find how to accomplish that.

Just put

```groovy
updateGitlabCommitStatus name: 'build', state: 'pending'
```

***BEFORE*** the outermost `pipeline` block in `Jenkinsfile`.

I haven't found the exact configuration needed to have this work, but I think it's worth trying.

- GitLab CE 10.0.4
- Jenkins 2.73.2
  - GitLab Plugin 1.5.0
  - Pipeline job with `Pipeline script from SCM` definition
