### ISSUE TITLE
Conflicting states of the build

### ISSUE THREAD

**Issue by AndreaCrotti** [jenkinsci/gitlab-plugin#478]
## Issue

Conflicting state of build status seen.

### Context
- **Gitlab plugin version**: 1.4.3
- **Gitlab version**: 8.14.1 e45bf3d
- **Jenkins version**: 2.19.4
- **Job type**: Freestyle.

### Problem description

I have an interesting problem now with setting build status on commits, and I'm not fully sure if it's gitlab or gitlab-plugin the issue.
I have a job in Jenkins that is called "$projectname-1" (for example) where in our gitlab is called $projectname.

Everything works fine, however I have an inconsistent version of the facts from the gitlab UI, as in the picture.
The two `failed` and `pending` point exactly to the same build, but obviously the result is not what's expected.
![selection_016](https://cloud.githubusercontent.com/assets/53640/21728564/c246e318-d43e-11e6-9b67-c130768d5dc8.png)

Any ideas? can it be related with the plugin itself?
Thanks

**Comment by AndreaCrotti** [comment]
Mm sorry I just realised the second was the previous build.
So the actual weird thing is that I get many pending statuses in various commits, but all the build actually terminates in one way or another.

Any idea about when a build gets into the pending state?
Thanks

**Comment by omehegan** [comment]
@AndreaCrotti you have submitted a lot of issues lately, but they are always lacking any information about how you have configured the plugin. Without that, it is impossible for me to help you troubleshoot. In this case I will need to see how you have configured your job for sending build status to GitLab. E.g. the post-build step where status is sent.

Also, with respect, I want to point out that the plugin has over 10,000 installations, and all the basic functionality is pretty much known to work. If you are having problems with things like triggering or reporting status back to GitLab, please review the documentation and make sure you are following it.

**Comment by sgautrin** [comment]
I have apparently the same issue as described here, using a freestyle jenkins job, with:

- jenkins 2.40
- gitlab 8.15.0 (54850bf)
- gitlab-plugin 1.4.4

I figured I'd rather update this issue with details on our setup, but if you'd rather I can create another issue for it.

Our job is configured like that:

- gitlab connection specified
- git repository via ssh

    + name: origin
    + refspec: `+refs/heads/*:refs/remotes/origin/* +refs/merge-requests/*/head:refs/remotes/origin/merge-requests/*`

- branches to build: `origin/${source_branch}` (we use a groovy script as Shared Objects that sets this variable from gitlabSourceBranch so we can also build the job manually
- triggers enabled: push events, merge request events, rebuild open merge requests on push to source or target
- post build action: publish build status to gitlab commit

And on gitlab side, we configured the hook on push and merge request events.

Below an extract of the log:

```text
WebHook called with url: /project/experiments/test-ci
PushBuildAction
Push: {
..
}
AbstractWebHookTriggerHandler handle 
experiments/test-ci triggered for push.
GitLabClientBuilder - Call GitLab:
POST /api/v3/projects/37/statuses/90c085d1d91d50d9a71aab2e8d6485c89f0c020b
Status: 201 Created
{
  "id": 344,
  "status": "pending"
}
GET /api/v3/projects/37/merge_requests?state=opened&page=1&per_page=100
Status: 200 OK -- no merge request open in this case
Retrieving gitlab project ids
GET /api/v3/projects/37/repository/commits/90c085d1d91d50d9a71aab2e8d6485c89f0c020b
Status: 200 OK
POST /api/v3/projects/37/statuses/90c085d1d91d50d9a71aab2e8d6485c89f0c020b
Status: 201 Created
{
  "id": 345,
  "status": "running"
}
Retrieving gitlab project ids
GET /api/v3/projects/37/repository/commits/90c085d1d91d50d9a71aab2e8d6485c89f0c020b
Status: 200 OK
POST /api/v3/projects/37/statuses/90c085d1d91d50d9a71aab2e8d6485c89f0c020b
Status: 201 Created
{
  "id": 345,
  "status": "success"
}
```

Plugin log does not specify what's sent in the POST request to `/api/v3/projects/37/statuses/90c085d1d91d50d9a71aab2e8d6485c89f0c020b`, but we can see that the first request creates the build 344 on gitlab with status “pending”, then the second creates the build 345 with status ”running“, and then the third updates the build 345 with status “success”. I would expect that the second call would update the build 344 created as “pending” instead of creating a new one.

As a result in gitlab, we get two builds in the pipeline pointing to the same jenkins job, 344 which stays “pending” and marked as “retried”, and 345 which is “success”.

To be noted that we didn't add the second repository described in the “iii. To be able to merge from forked repositories” section of the README as we don't need to merge from forked repositories.

[Edit 2017-01-16] I had forgotten in our job setup to mention the gitlab connection configuration, and the post build action for publishing build status to gitlab commit

**Comment by omehegan** [comment]
Duplicated by #489.
