### ISSUE TITLE
[Question] Seeking maintainers?

### ISSUE THREAD

**Issue by tomasbjerre** [jenkinsci/gitlab-plugin#519]
The readme says **[Seeking maintainers](https://github.com/jenkinsci/gitlab-plugin#seeking-maintainers)**, also the wiki says **[This plugin is up for adoption](https://wiki.jenkins-ci.org/display/JENKINS/GitLab+Plugin)**.

But I've also seen [this thread](https://groups.google.com/forum/#!searchin/jenkinsci-dev/gitlab$20plugin%7Csort:relevance/jenkinsci-dev/7A7MRbVkePg/6EDXy9kyFQAJ) that sounds like its no longer an issue.

And don't get me wrong now =) I understand if the maintainers can't respond immediately to support cases. But [my PR](https://github.com/jenkinsci/gitlab-plugin/pull/510) was submitted 11 days ago without response. So just wanted to ask about the state of the plugin regarding maintenance?

The wiki and readme should probably be updated.

**Comment by omehegan** [comment]
@tomasbjerre my apologies, normally I try to respond to PRs and issues within a couple of days, but I've been busier than usual lately.

@trance1st and @colourmeamused have been made maintainers, but I am still open to the idea of getting more people involved (I have not heard a lot from them yet, presumably they are busy with other things!). So that's why I haven't yet removed the wiki and doc entries - if another person wants to join in and start hacking right away, I'd welcome it!

**Comment by omehegan** [comment]
We're good for maintainers now, and I am committing to doing releases at least monthly moving forward.
