### ISSUE TITLE
Build history not displayed on GitLab

### ISSUE THREAD

**Issue by CSobol** [jenkinsci/gitlab-plugin#545]
### Context
- **Gitlab plugin version**: 1.2.2
- **Gitlab version**: 8.7
- **Jenkins version**: 1.634
- **Job type**: Freestyle

### Problem description

Create pull request - see build pass
Push additional code - See rebuild pass
Update merge request - see rebuild pass

**Expected outcome:** View build history on gitlab and see three entries . 
**Actual outcome:** Only most recent build is displayed

**Comment by omehegan** [comment]
Your versions of the plugin, GitLab, and Jenkins are all fairly old, so we probably will not be able to invest time in debugging this for you. It's just as likely to be an issue on the GitLab side as it is with our plugin. I will point out that our README includes this note: "#272 - Plugin version 1.2.0+ does not work with GitLab Enterprise Edition < 8.8.3, due to a bug on their side." So if you are using GitLab EE, you may be experiencing at least one known bug.

Also note that the same section of the README has a warning about manual configuration changes you will need to make if you upgrade Jenkins past the version you are currently using (and I would recommend that you do that, because there have been numerous security vulnerabilities published in the last year which affect all versions older than the current LTS).
