### ISSUE TITLE
GitLab environment variables and multi-branch pipeline jobs

### ISSUE THREAD

**Issue by AnthonyMastrean** [jenkinsci/gitlab-plugin#569]
### Context
- **Gitlab plugin version**: 1.4.5
- **Gitlab version**: 9.0 CE
- **Jenkins version**: 2.63
- **Job type**: Multi-branch pipeline

### Problem description

Your readme says you can't get GitLab environment variables into the multi-branch pipeline.

![image](https://user-images.githubusercontent.com/217842/27542407-28c7e190-5a55-11e7-9fe4-fc58654919dd.png)

https://github.com/jenkinsci/gitlab-plugin#git-configuration-for-multibranch-pipelineworkflow-jobs

What I'm not sure about is this... is this a "bug" in your plugin that can be fixed? Is this a bug in the SCM or pipeline underpinnings in Jenkins? If it's the latter, is there an upstream bug report? If no, I'm happy to submit that.

I'm getting a sense that multi-branch pipelines are going to be pushed as the default kind of job to configure.

It would be awesome if this all worked as expected :)

**Comment by omehegan** [comment]
It's to do with the way Jenkins Pipeline implements multibranch jobs. It just does not provide a facility for external services to pass data around in these instances, I guess because there isn't much of a use case for it. So this is something you would have to take up with the Pipeline Multibranch plugin.

**Comment by XonqNopp** [comment]
@AnthonyMastrean did you report this upstream?
