### ISSUE TITLE
System hooks not working for latest gitlab 

### ISSUE THREAD

**Issue by bmaehr** [jenkinsci/gitlab-plugin#590]
[EDIT]Sorry, this was for the gitlab-hook-plugin instead of gitlab-plugin[/EDIT]

## Issue
Gitlab has changed the structure of the webhook messages. The repository url is not detected anymore.

### Context
- **Gitlab plugin version**: 1.4.6
- **Gitlab version**: 9.3.6
- **Jenkins version**: 2.69
- **Job type**: Freestyle

### Problem description

Gitlab has changed the structure of the webhook messages:

Note: Starting from GitLab 8.5:

the repository key is deprecated in favor of the project key
the project.ssh_url key is deprecated in favor of the project.git_ssh_url key
the project.http_url key is deprecated in favor of the project.git_http_url key

https://docs.gitlab.com/ce/user/project/integrations/webhooks.html

**Comment by omehegan** [comment]
@bmaehr it's not clear to me from the doc you linked to that these keys have actually been removed. It just says they are deprecated. Can you follow the instructions in the User Support section of the README for increasing logging for the plugin, and then include the log which shows the JSON payload it receives from GitLab? That will help us figure out where the problem is. Also, was this working for you until you upgraded GitLab or something?

**Comment by bmaehr** [comment]
The sent message is according to the request body in the link.

With the older Gitlab version it is working.

**Comment by bmaehr** [comment]
Sorry, this was for the gitlab-hook-plugin instead of gitlab-plugin

**Comment by Pitority** [comment]
Here the link [to the issue in the gitlab-hook-plugin project ](https://github.com/jenkinsci/gitlab-hook-plugin/issues/41)
