### ISSUE TITLE
No build status on merge request from forks

### ISSUE THREAD

**Issue by rfgamaral** [jenkinsci/gitlab-plugin#61]
If you look at this screenshot:

![origin](https://cloud.githubusercontent.com/assets/96476/6624498/92e3e77a-c8e1-11e4-8780-9e056ac6a641.png)

The build status `CI build failed for...` is there. This is a merge request from a branch on `origin` to `origin/master`.

If you look at this one:

![fork](https://cloud.githubusercontent.com/assets/96476/6624510/aff2b0bc-c8e1-11e4-8213-db25430aa8e7.png)

There's no build status. This is a merge request from a branch on a fork to `origin/master`.

But both triggered a build on the Jenkins CI serve as you can see from the Jenkins Bot User comments. Also, following pushes to the same branch don't make new Jenkins builds (thus no new comment from Jenkins Bot User) for forks, but these comments appear for each push on `origin` branches.

**Conclusion:**
- Branches on `upstream`:
 + Build status is shown and updated for each push.
 + Jenkins Bot User comments when the MR is first created and after a push of commit(s).
- Branches on a fork:
 + Build status is never shown.
 + Jenkins Bot User comments only for the **first** build when the MR is created.

Am I missing some configuration or is this a bug?

**Comment by dilcom** [comment]
Faced with that issue today too. 
Seems like gitlab uses CI binded to fork instead of one binded to target repository. Mentioned it in gitlab issue tracker https://github.com/gitlabhq/gitlabhq/issues/9013 . I fixed in my gitlab but still have some problems so I think plugin should be fixed too.
As I see plugin links commit SHA1 with build number for merge requests and it works well for merge requests between branches in one repository. It doesn't work for merges from another repository. For any reason page //jenkins.root/project_name/commits/Sha1 is empty. Build triggered by such merge request have wrong revision (SHA1 of last commit in TARGET branch instead of one from source branch).

**Comment by rfgamaral** [comment]
@dilcom How did you fix this on your GitLab? Still having this problem...

**Comment by rfgamaral** [comment]
@bassrock Would it be possible to get some input from you?

**Comment by omehegan** [comment]
@rfgamaral are you still having this issue? It sounds like a probable bug or limitation on the GitLab side, rather than with the plugin.

**Comment by coder-hugo** [comment]
This is definitively a bug/limitation on the GitLab side. GitLab doesn't send any request for retrieving the build status to the jenkins for a MR of a fork unless the jenkins is configured as GitLab CI in the forked repo, too. So we can't fix anything on our side.
