### ISSUE TITLE
How  retrieval the `commit message` in pipeline

### ISSUE THREAD

**Issue by jiahut** [jenkinsci/gitlab-plugin#800]
the `gitlab webhook` had already send the lastCommit message , How  retrieval the `commit message` in pipeline

**Comment by omehegan** [comment]
https://github.com/jenkinsci/gitlab-plugin#defined-variables is the list of variables we populate. If the thing you want is not there, I would suggest you just run a `git show` or equivalent command in a shell during the build, and pull the result into a Pipeline variable.

**Comment by jiahut** [comment]
I need follow the `commit message` to determine checkout the code or not  in my case.
@omehegan  think you all the same

**Comment by BuhtigithuB** [comment]
Please reopen this, I need the commit message badly to be able to prevent feedback loop that occur because CI commit... ci-skip leave Gitlab merge button red... We already have gitlabMergeRequestLastCommit which is the SHA1 Hash... So how hard could it be to add the commit message... I am not so sure what is mergeCommitMessage : https://github.com/jenkinsci/gitlab-plugin/search?q=mergeCommitMessage&unscoped_q=mergeCommitMessage

And why we don't have it already in the defined variables...

Is not having commit message in defineds variables a limitation that is coming from Gitlab/Webhook???

Thanks to clarify
