### ISSUE TITLE
Spaces in Jenkins job name causes CI Status to not update 

### ISSUE THREAD

**Issue by ndcampbell** [jenkinsci/gitlab-plugin#85]
I am getting the error "Cannot connect to the CI server." on Merge Requests in Gitlab ever since upgrading to 7.10.5-ee.  This is happening for any project where my Jenkins job name has a space in it. The projects still build and everything, just the status says it cannot connect. If I remove spaces from the job name, it works. This was working just fine in 7.10.0-ee. 
 
I am using the most recent version of the plugin. I checked the production.log in gitlab and see:

Started GET "/venus-platform/venus/merge_requests/165/ci_status" for 127.0.0.1 at 2015-05-29 08:17:36 -0500

and in the Jenkins log I see:

May 29, 2015 8:21:58 AM com.dabsquared.gitlabjenkins.GitLabWebHook getDynamic
INFO: WebHook called with url: /refs/bug-changeBgcEnumToEspd/commits/97b19a8d6a6cb52c8faaf6f55588270dadbc3a33/status.json

Any ideas? 

Jenkins URLs use "%20" for spaces. Perhaps a parsing error? 

![image](https://cloud.githubusercontent.com/assets/5134555/7883231/918b2556-05da-11e5-8fad-9136505f7abd.png)

**Comment by ndcampbell** [comment]
I found the connection as to why one project was working. The CI Status is not working for any projects where Jenkins has a space in the name. If I remove all the spaces from my Jenkins jobs name, the CI Status in Gitlab updates correctly. Jenkins URLs use "%20" for spaces, perhaps there is a parsing issue?

**Comment by thatarchguy** [comment]
+1 I experienced this as well.

**Comment by omehegan** [comment]
Confirmed, still a bug in the latest version.

**Comment by coder-hugo** [comment]
This is a bug in GitLab 7.14. It forces you to enter a valid URL that contains slashes already URL encoded (%20) but does an URL encoding itself before requesting the status.json. This second URL encoding changes the % sign to %25. As the Jenkins does the URL decoding just once (for a reason) the gitlab-plugin gets a project name that contains a %20 instead of a space.
I'd suggest you to use URL friendly names (names that not contain any sign that needs to be URL encoded) for your Jenkins jobs. If you like to have a more human readable name for the job in the overview page use the displayName of the advanced project options for this.
