### ISSUE TITLE
Commit status stuck on "pending" in status.json

### ISSUE THREAD

**Issue by alekstorm** [jenkinsci/gitlab-plugin#86]
It looks like there were two groups of users describing the same symptoms in #56, but suffering from different underlying causes. Myself and @twk3, at least, are in the group whose problem was not fixed by #76.

I was able to track the introduction of the bug down to a single commit: 6ad6804cb49bef4df5144d218a8c7885b778b197. I'm not a domain expert, so I can't speculate further on what part of the commit is the culprit, but the affected code regions certainly seem to make sense.

**Comment by twk3** [comment]
My setup that I found that didn't work with the later version plugins was:
- Not using the merge request webhook
- Not using the merge before build option
- Building all branches

The use case, is when you are building on pushed to all branches, and you don't care about testing the actual mergeability in jenkins, (being that GitLab already restricts you from merging, stopping it here was pointless with our workflow, where you aren't allowed to merge until the tests pass on your commit) But we want the merge request page to show the last passing build for the branch.

In this setup the getBuildBySHA1 will never have a mergeRecord, and isMergeRequestBuild will always be false (because source and target branches are always the same), combined with that requesting the status.json is considered a 'triggeredByMergeRequest' request, means that the build we are looking for gets skipped over.

**Comment by rps** [comment]
Looks like build status.json was introduced in dd047dca

**Comment by omehegan** [comment]
@twk3 what version of Jenkins are you using?

**Comment by twk3** [comment]
@omehegan Jenkins 1.580.3

**Comment by omehegan** [comment]
@twk3 We're (me, @rps, @alekstorm) on 1.609.3 and have had this problem for the last few LTS releases. The problem is that mainBuild is always null here: https://github.com/DABSquared/gitlab-plugin/blob/master/src/main/java/com/dabsquared/gitlabjenkins/GitLabWebHook.java#L223  Working on figuring out why that is.

**Comment by omehegan** [comment]
https://github.com/DABSquared/gitlab-plugin/commit/6ad6804cb49bef4df5144d218a8c7885b778b197#commitcomment-13882903 is the problem. I don't understand the logic of skipping push-triggered builds.

**Comment by omehegan** [comment]
@twk3 are you by any chance using matrix/multi-configuration builds?

**Comment by twk3** [comment]
Using multijob buildsteps, but the gitlab-plugin on is the parent job. Not using matrix.

**Comment by omehegan** [comment]
@twk3 try building https://github.com/omehegan/gitlab-plugin/tree/fix_stuck_in_pending and see if it fixes the problem for you.

**Comment by omehegan** [comment]
@twk3 did you see my comment above? I'd like to merge the change but preferably after you have a chance to try it.

**Comment by omehegan** [comment]
Known bug, I think I have a fix.
