### ISSUE TITLE
Add an additional variable to determine will the source branch be removed in MR

### ISSUE THREAD

**Issue by ghost** [jenkinsci/gitlab-plugin#932]
### The future request
It is a more likely the feature request. I have been using gitlab-plugin on Merge Requests. As you can see in Defined variables there is no variable like **gitlabSourceBranchRemove** so it is unable to determine if the source branch will be removed after MR is merged. Please add this variable it will be helpful. Thanks in advance

**Comment by kadauber** [comment]
Seconded - I'm using this plugin in my day job, and it works great!

At the very least, when I call "acceptGitLabMR" in my Jenkinsfile, I would like the default value for "removeSourceBranch" to be the value of the checkbox in the GitLab UI. Currently the behavior appears to be:

1. If a value is specified in the Jenkinsfile e.g. acceptGitLabMR (removeSourceBranch: true), it uses the value provided
2. Otherwise, use false

I would like the behavior to be:
1. If a value is specified in the Jenkinsfile e.g. acceptGitLabMR (removeSourceBranch: true), it uses the value provided
2. If the checkbox labeled "Delete source branch when merge request is accepted." was checked, use true
3. Otherwise, use false

Thanks!

**Comment by UnsolvedCypher** [comment]
@kadauber's desired behavior is now implemented by #1220, which I think is the only use case for this variable. Unless someone has another use for this feature I think this issue can be closed.

**Comment by basil** [comment]
Fixed in #1220
