### ISSUE TITLE
Need Help!!!!! ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job. Finished: FAILURE

### ISSUE THREAD

**Issue by digheTest** [jenkinsci/gitlab-plugin#959]
Need Help!!!!!
I was trying to create CI/CD pipeline through Jenkins and followed below steps(Error1.jpg to Error2.jpg). When I had started my Job every time i faced this issue(Error5.jpg
![Error1](https://user-images.githubusercontent.com/52630126/62542596-b6dcfb80-b879-11e9-81da-e04ec93cc38a.jpg)
![Error2](https://user-images.githubusercontent.com/52630126/62542597-b7759200-b879-11e9-9ebc-479deb0124d0.jpg)
![Error3](https://user-images.githubusercontent.com/52630126/62542599-b7759200-b879-11e9-8349-053d110aec50.jpg)
![Error4](https://user-images.githubusercontent.com/52630126/62542600-b7759200-b879-11e9-972c-d4d82bf2b7c6.jpg)
![Error5](https://user-images.githubusercontent.com/52630126/62542603-b80e2880-b879-11e9-95a9-05cecfe02b02.jpg)

)

_Originally posted by @digheTest in https://github.com/jenkinsci/gitlab-plugin/issues/539#issuecomment-518662655_

**Comment by dblessing** [comment]
@digheTest 

A few things:

- When dealing with open-source communities, remember that you're usually dealing with volunteers. People are doing this because they enjoy it, and they aren't getting paid. So when you start with 'NEED HELP!!' it's really unnecessary. Just open a normal issue and people will reply when able. 
- This is the repository for the Jenkins '**GitLab** Plugin'. As far as I can tell, you're not using GitLab, since you're cloning from a **GitHub.com** URL. Unless I've missed something, your problem has nothing to do with this plugin.

**Comment by dblessing** [comment]
By the way, @digheTest, I see this is your first issue, and you've only recently joined GitHub. Welcome to the world of open-source! Jumping in and taking that first step is sometimes hard, so good job. We all need a little direction in the beginning so don't worry about it. Just make sure you're in the right place, and have patience. If you need immediate help with something then paid support from the respective provider (Jenkins, GitHub, GitLab, etc) might be necessary.

**Comment by digheTest** [comment]
@dblessing  Thanks a ton for comments and warm Welcome for beginner. I will make sure to raise a issue to respective provider. Thank you again!!!

**Comment by digheTest** [comment]
..

**Comment by vij-code** [comment]
why paid support for simple issues, and why this ticket showing closed?? without resolution
